#!/usr/bin/env rake

require 'rspec/core/rake_task'

# default environment values if not set
ENV['SELENIUM_URL']||="" # mandatory
ENV['SELENIUM_HOST']||="ondemand.saucelabs.com"
ENV['SELENIUM_PORT']||="80"
ENV['SELENIUM_USERNAME']||="csanchez"
ENV['SELENIUM_ACCESS_KEY']||="65e90c28-1d58-41b5-a3dc-2f1e14bb7fd6"
ENV['SELENIUM_OS']||="Windows 2003"
ENV['SELENIUM_BROWSER']||="firefox"
ENV['SELENIUM_BROWSER_VERSION']||="7"

RSpec::Core::RakeTask.new(:spec) do |t|
  t.rspec_opts = '--tag selenium:1' # run only selenium 1 tests
end

task :default => :spec
